# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/yigitozgumus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake"

# The command to remove a file.
RM = "/Users/yigitozgumus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/yigitozgumus/Code/Workspace/ClionProjects/SCC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/yigitozgumus/Code/Workspace/ClionProjects/SCC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/yigitozgumus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/yigitozgumus/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/181.5087.36/CLion.app/Contents/bin/cmake/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yigitozgumus/Code/Workspace/ClionProjects/SCC/CMakeFiles /Users/yigitozgumus/Code/Workspace/ClionProjects/SCC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/yigitozgumus/Code/Workspace/ClionProjects/SCC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Project

# Build rule for target.
Project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Project
.PHONY : Project

# fast build rule for target.
Project/fast:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/build
.PHONY : Project/fast

src/analyzer.o: src/analyzer.cpp.o

.PHONY : src/analyzer.o

# target to build an object file
src/analyzer.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/analyzer.cpp.o
.PHONY : src/analyzer.cpp.o

src/analyzer.i: src/analyzer.cpp.i

.PHONY : src/analyzer.i

# target to preprocess a source file
src/analyzer.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/analyzer.cpp.i
.PHONY : src/analyzer.cpp.i

src/analyzer.s: src/analyzer.cpp.s

.PHONY : src/analyzer.s

# target to generate assembly for a file
src/analyzer.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/analyzer.cpp.s
.PHONY : src/analyzer.cpp.s

src/experiment.o: src/experiment.cpp.o

.PHONY : src/experiment.o

# target to build an object file
src/experiment.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/experiment.cpp.o
.PHONY : src/experiment.cpp.o

src/experiment.i: src/experiment.cpp.i

.PHONY : src/experiment.i

# target to preprocess a source file
src/experiment.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/experiment.cpp.i
.PHONY : src/experiment.cpp.i

src/experiment.s: src/experiment.cpp.s

.PHONY : src/experiment.s

# target to generate assembly for a file
src/experiment.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/experiment.cpp.s
.PHONY : src/experiment.cpp.s

src/graphcomponent.o: src/graphcomponent.cpp.o

.PHONY : src/graphcomponent.o

# target to build an object file
src/graphcomponent.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/graphcomponent.cpp.o
.PHONY : src/graphcomponent.cpp.o

src/graphcomponent.i: src/graphcomponent.cpp.i

.PHONY : src/graphcomponent.i

# target to preprocess a source file
src/graphcomponent.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/graphcomponent.cpp.i
.PHONY : src/graphcomponent.cpp.i

src/graphcomponent.s: src/graphcomponent.cpp.s

.PHONY : src/graphcomponent.s

# target to generate assembly for a file
src/graphcomponent.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/graphcomponent.cpp.s
.PHONY : src/graphcomponent.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/nuutila.o: src/nuutila.cpp.o

.PHONY : src/nuutila.o

# target to build an object file
src/nuutila.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/nuutila.cpp.o
.PHONY : src/nuutila.cpp.o

src/nuutila.i: src/nuutila.cpp.i

.PHONY : src/nuutila.i

# target to preprocess a source file
src/nuutila.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/nuutila.cpp.i
.PHONY : src/nuutila.cpp.i

src/nuutila.s: src/nuutila.cpp.s

.PHONY : src/nuutila.s

# target to generate assembly for a file
src/nuutila.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/nuutila.cpp.s
.PHONY : src/nuutila.cpp.s

src/pearce.o: src/pearce.cpp.o

.PHONY : src/pearce.o

# target to build an object file
src/pearce.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/pearce.cpp.o
.PHONY : src/pearce.cpp.o

src/pearce.i: src/pearce.cpp.i

.PHONY : src/pearce.i

# target to preprocess a source file
src/pearce.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/pearce.cpp.i
.PHONY : src/pearce.cpp.i

src/pearce.s: src/pearce.cpp.s

.PHONY : src/pearce.s

# target to generate assembly for a file
src/pearce.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/pearce.cpp.s
.PHONY : src/pearce.cpp.s

src/tarjan.o: src/tarjan.cpp.o

.PHONY : src/tarjan.o

# target to build an object file
src/tarjan.cpp.o:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/tarjan.cpp.o
.PHONY : src/tarjan.cpp.o

src/tarjan.i: src/tarjan.cpp.i

.PHONY : src/tarjan.i

# target to preprocess a source file
src/tarjan.cpp.i:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/tarjan.cpp.i
.PHONY : src/tarjan.cpp.i

src/tarjan.s: src/tarjan.cpp.s

.PHONY : src/tarjan.s

# target to generate assembly for a file
src/tarjan.cpp.s:
	$(MAKE) -f CMakeFiles/Project.dir/build.make CMakeFiles/Project.dir/src/tarjan.cpp.s
.PHONY : src/tarjan.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Project"
	@echo "... src/analyzer.o"
	@echo "... src/analyzer.i"
	@echo "... src/analyzer.s"
	@echo "... src/experiment.o"
	@echo "... src/experiment.i"
	@echo "... src/experiment.s"
	@echo "... src/graphcomponent.o"
	@echo "... src/graphcomponent.i"
	@echo "... src/graphcomponent.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/nuutila.o"
	@echo "... src/nuutila.i"
	@echo "... src/nuutila.s"
	@echo "... src/pearce.o"
	@echo "... src/pearce.i"
	@echo "... src/pearce.s"
	@echo "... src/tarjan.o"
	@echo "... src/tarjan.i"
	@echo "... src/tarjan.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

